apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose-eks.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  labels:
    io.kompose.service: vets-service-java
  name: vets-service-java
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vets-service-java
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose-eks.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      labels:
        io.kompose.service: vets-service-java
      annotations:
        sidecar.opentelemetry.io/inject-java: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      serviceAccountName: visits-service-account
      containers:
        - command:
            - ./dockerize
            - -wait=tcp://discovery-server:8761
            - -timeout=60s
            - --
            - java
            - org.springframework.boot.loader.JarLauncher
          env:
            - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
              value: "http://otel-collector.default.svc.cluster.local:4317"
            - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
              value: "grpc"
          image: 111122223333.dkr.ecr.us-west-2.amazonaws.com/springcommunity/spring-petclinic-vets-service:latest
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
          name: vets-service-java
          ports:
            - containerPort: 8083
      restartPolicy: Always
status: {}
